from flask import current_app
from datetime import datetime, timezone, timedelta
from flask_mail import Message as MailMessage
import uuid
from loguru import logger


class EmailService:
    def __init__(self, mail):
        self.mail = mail

    def send_verification_email(self, email, registration_session):
        verification_code = registration_session.verification_code
        token = str(uuid.uuid4())
        registration_session.verification_token = token
        registration_session.verification_attempt_expiry = datetime.now(
            timezone.utc
        ) + timedelta(minutes=15)
        registration_session.save()

        verification_link = (
            f"{current_app.config['REACT_APP_BACKEND_URL']}/auth/verify-email/{token}"
        )
        html_content = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body>
            <div class="container">
                <h2>Email Verification</h2>
                <p>Thank you for signing up! To complete your registration, please verify your email address using one of the following methods:</p>
                <h3>Method 1: Verification Code</h3>
                <p>Your verification code is: <strong>{verification_code}</strong></p>
                <p>Please enter this code on the registration page to verify your email.</p>
                <h3>Method 2: Verification Link</h3>
                <p>Alternatively, you can click the button below to verify your email:</p>
                <p>
                    <a href="{verification_link}" class="button">Verify Email</a>
                </p>
                <p>If the button above doesn't work, you can also copy and paste the following link into your browser:</p>
                <p>{verification_link}</p>
                <div class="footer">
                    <p>If you didn't request this verification, please ignore this email.</p>
                    <p>&copy; Acaceta, {datetime.now().year}. All rights reserved.</p>
                </div>
            </div>
        </body>
        </html>
        """
        msg = MailMessage(
            "Acaceta Email Verification", recipients=[email], html=html_content
        )
        logger.info(f"Sending verification email to {email}")
        self.mail.send(msg)

    def send(self, msg):
        self.mail.send(msg)

    def send_email_to_admin(self, title, file_url):
        """Send an email notification to the admin with the document title and S3 file URL."""
        subject = "New Document Uploaded for Review"
        html_content = f"""
        <p>A new document has been uploaded to the public index:</p>
        <p>Title: {title}</p>
        <p>S3 URL: <a href="{file_url}">{file_url}</a></p>
        <p>Please review the document and decide whether to add it to the public database.</p>
        """
        msg = MailMessage(subject, recipients=["info@acaceta.com"], html=html_content)
        self.mail.send(msg)

    def send_qr_code_email(self, email: str, link: str, document_title: str):
        """
        Send an email containing a QR code link for document sharing.

        Args:
            email (str): Recipient's email address
            link (str): The generated QR code link
            document_title (str): Title of the shared document
        """
        subject = f"QR Code Link for {document_title}"
        html_content = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body>
            <div class="container">
                <h2>Document Sharing Link</h2>
                <p>A document has been shared with you: <strong>{document_title}</strong></p>

                <p>You can access the document using the following link:</p>
                <p>
                    <a href="{link}" style="
                        background-color: #4CAF50;
                        border: none;
                        color: white;
                        padding: 15px 32px;
                        text-align: center;
                        text-decoration: none;
                        display: inline-block;
                        font-size: 16px;
                        margin: 4px 2px;
                        cursor: pointer;
                        border-radius: 4px;">
                        View Document
                    </a>
                </p>

                <p>Or copy this link to your browser:</p>
                <p>{link}</p>

                <div class="footer" style="margin-top: 20px; padding-top: 20px; border-top: 1px solid #eee;">
                    <p>This link was generated by Acaceta. If you didn't expect this email, please ignore it.</p>
                    <p>&copy; Acaceta, {datetime.now().year}. All rights reserved.</p>
                </div>
            </div>
        </body>
        </html>
        """

        msg = MailMessage(subject, recipients=[email], html=html_content)
        logger.info(
            f"Sending QR code link email to {email} for document: {document_title}"
        )
        self.mail.send(msg)
