name: acaceta-test

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    command: tail -f /dev/null  # Keep container running
    volumes:
      - ./backend:/app
      - tmp-data:/tmp
    networks:
      - test-network
    depends_on:
      mongodb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    command: mongod --port 27019
    ports:
      - "27019:27019"
    volumes:
      - mongo_test_data:/data/db
    networks:
      - test-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27019/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
    ports:
      - "9201:9200"
    networks:
      - test-network
    healthcheck:
      test: curl -s http://localhost:9200/_cluster/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongo_test_data:
  tmp-data:

networks:
  test-network:
    driver: bridge
