FROM python:3.12.4

# Environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    POETRY_VERSION=1.8.3 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1 \
    PATH="/opt/poetry/bin:$PATH" \
    PYTHONPATH="/app" \
    FLASK_ENV=testing \
    TESTING=true

# Create non-root user
RUN useradd -ms /bin/sh -u 1001 app

# Install poetry plugin and test dependencies
RUN pip install poetry-plugin-export pytest pytest-xdist pytest-asyncio pytest-cov mongoengine mongomock

# Set working directory and create it with proper permissions
WORKDIR /app
RUN chown app:app /app

# Copy dependency files
COPY --chown=app:app ./poetry.lock ./poetry.lock
COPY --chown=app:app ./pyproject.toml ./pyproject.toml

# Install dependencies
RUN poetry export -f requirements.txt --output requirements.txt
RUN pip install -r requirements.txt --log pip.log

# Create and set up temporary directory
RUN mkdir -p /app/tmp && chown -R app:app /app/tmp

# Copy environment files
COPY --chown=app:app .env /app/.env
COPY --chown=app:app .env.test /app/.env.test

# Copy project files
COPY --chown=app:app . .

# Switch to non-root user
USER app

# Install NLTK data
RUN python3 -m nltk.downloader punkt_tab

# Add test directory to Python path
ENV PYTHONPATH="${PYTHONPATH}:/app/tests"
