apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdk8s-frontend-deployment-frontend-deployment-c83dfb68
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: 253490794427.dkr.ecr.us-west-1.amazonaws.com/acaceta_frontend:latest
          name: frontend
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
