apiVersion: v1
kind: Service
metadata:
  name: cdk8s-elasticsearch-service-elasticsearch-service-c83bfbef
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
  type: ClusterIP
